# Generated by Django 5.0 on 2023-12-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cetegory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cetegory'),
        ),
    ]
